# Generated by Django 4.2.2 on 2024-04-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamhistory',
            old_name='stream',
            new_name='room',
        ),
    ]
