# Generated by Django 4.1.7 on 2023-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_unique_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
