# Generated by Django 4.1.7 on 2023-07-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
        ('users', '0003_room_room_unique_id_alter_room_room_password'),
    ]

    operations = [
    ]
