# Generated by Django 4.1.7 on 2023-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20230717_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(max_length=50),
        ),
    ]
