# Generated by Django 4.1.7 on 2023-07-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
