# Generated by Django 4.1.7 on 2023-07-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_room_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
