# Generated by Django 4.1.7 on 2023-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_room_room_name_alter_room_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default="<function User.__str__ at 0x10b0712d0>'s room", max_length=100),
        ),
    ]
