# Generated by Django 4.2.2 on 2023-07-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
