# Generated by Django 4.2.2 on 2023-07-19 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_room_room_name_alter_room_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
