# Generated by Django 4.2.3 on 2023-07-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_stream'),
        ('users', '0019_alter_room_room_name'),
    ]

    operations = [
    ]
