# Generated by Django 4.2.3 on 2023-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_0017_stream_0019_alter_room_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_room',
            new_name='assigned_room',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='stream_link',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
