# Generated by Django 4.2.2 on 2023-07-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_room_room_name'),
        ('users', '0021_alter_room_room_name'),
    ]

    operations = [
    ]
