# Generated by Django 4.2.3 on 2023-07-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_stream_room_stream_assigned_room_and_more'),
        ('users', '0024_alter_room_room_name'),
    ]

    operations = [
    ]
