# Generated by Django 4.2.2 on 2023-07-21 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_userroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_owner',
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_room', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='users_room', through='users.UserRoom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
