# Generated by Django 4.2.2 on 2023-07-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_room_room_owner_room_owner_room_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
