# Generated by Django 4.2.2 on 2023-07-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_userroom_date_joined_userroom_date_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroom',
            name='date_left',
        ),
    ]
