# Generated by Django 4.2.2 on 2023-07-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wt_mobile', '0003_userroom_room_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userroom',
            table='wt_mobile_room_participants',
        ),
    ]
